### ISSUE TITLE
Crash when opening editor

### ISSUE THREAD

**Issue by tronta** [konradsz/igrep#1]
When opening the editor the application crashes for me with

```
panicked at 'Error: Failed to run editor.: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/petsoi/.cargo/registry/src/github.com-1ecc6299db9ec823/igrep-0.1.2/src/ig/mod.rs:49:22                                                          stack backtrace:
0: rust_begin_unwind at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/panicking.rs:143:14
2: core::result::unwrap_failed at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/result.rs:1749:5
3: ig::ig::Ig::open_file_if_requested 4: ig::main note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Fedora 35

**Comment by konradsz** [comment]
Thanks for reporting this issue.
Does it happen for any match `igrep` finds for you? Can you provide a command you used?

**Comment by tronta** [comment]
I just tried `ig test .` and yes with any try.
I now remember that I aliased `vim=nvim`… maybe this is the issue.

**Comment by konradsz** [comment]
You can always try to pass `--editor neovim` option to run neovim explicitly, however it looks like the path to the file `igrep` found does not exist. Does the path looks correct i.e. points to an existing file?
I should probably improve the error message to display the path :)

**Comment by tronta** [comment]
I tried `ig test .` and yes it failed on all results-

**Comment by konradsz** [comment]
I read the error message you provided incorrectly, turns out it might be a problem with running editor itself. In version [v0.2.0](https://github.com/konradsz/igrep/releases/tag/v0.2.0) I improved this message to print also the command `igrep` is trying to execute, so this should shed some light on a problem.

**Comment by tronta** [comment]
Sorry for not following up on it, but it just got lost.
In the mean time I updated heavier my OS, but it seams to work with the  0.3 version.
Many thanks for you effort!
