### ISSUE TITLE
Use ripgrep config file

### ISSUE THREAD

**Issue by kbd** [konradsz/igrep#11]
ripgrep supports a configuration file:

https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#configuration-file

It would be nice if igrep respected ripgrep's config file so that I can use the same config for both.

**Comment by konradsz** [comment]
Thank your for your suggestion! I like this idea, `igrep` options are always going to be a subset of `ripgrep` options, so it could respect its config file.

**Comment by kbd** [comment]
Hi, thanks for implementing this! Just tried it out and it doesn't seem to respect some of the config I'm using:


![Screen Shot 2022-04-24 at 2 05 41 PM](https://user-images.githubusercontent.com/728060/164994570-254dc62b-8642-438f-b8f5-0bbe1ebe87ea.png)

![Screen Shot 2022-04-24 at 2 04 41 PM](https://user-images.githubusercontent.com/728060/164994523-a178672e-e570-46b8-b3f5-4a593fd17a92.png)

**Comment by konradsz** [comment]
I guess you are talking about `--colors` option? This isn't used by `igrep` unfortunately! Only those listed in README are currently supported.
