### ISSUE TITLE
Support open files in VSCode

### ISSUE THREAD

**Issue by wilbeibi** [konradsz/igrep#13]
Not sure whether you interested in adding vscode, it support open files from command line via `code -g <file_name>:<line_number>` , I can also send a PR in the weekend (or keep it in my own forked branch if it not fit your roadmap).

**Comment by konradsz** [comment]
I am not opposed to adding support for vscode, I quickly hacked the solution and it seems to work just fine :) if you wish to contribute your PR welcome - I would consider moving process spawn to `editor.rs` in this case. If you prefer to wait, I will take care of an implementation soon.
