### ISSUE TITLE
Release binary for Windows

### ISSUE THREAD

**Issue by rashil2000** [konradsz/igrep#19]
A binary GitHub release asset for Windows would make usage of igrep very easy. The target triple is `x86_64-pc-windows-msvc`

This will also allow us to install igrep through Scoop package manager, by creating a manifest (similar to Brew tap). I can make a PR for this.

**Comment by konradsz** [comment]
I added zip compressed `ig` binary to latest release, hope it will suffice. If you are willing to contribute your PR is welcome!
