### ISSUE TITLE
Error: `Initial console modes not set` on Windows

### ISSUE THREAD

**Issue by rashil2000** [konradsz/igrep#3]
Hey!

I saw the reddit post and found the project really cool! I ran the `cargo install igrep` command on Windows 10, and compilation was successful. However, running any command results in an error:

![cursor2](https://user-images.githubusercontent.com/46838874/156372195-089641e1-1854-41b9-b837-fbafe5c4d480.gif)

Scouring through the crossterm source, I found this line https://github.com/crossterm-rs/crossterm/blob/e920d0cfd7819752b050ace40471af6f6529904c/src/event/sys/windows.rs#L36 to be the culprit. Maybe we need to call an initialization function before drawing the UI?

**Comment by konradsz** [comment]
Hey, I am glad to hear that you like this project!

When it comes to Windows support - I should be more clear in README that my aim is to support macOS and Linux (I just added such note). I am not sure how much effort is needed to make it working on Windows, so I cannot promise it ever will. But I will give it a try :)

**Comment by rashil2000** [comment]
Thanks, let me know if any testing is needed!

**Comment by ErichDonGubler** [comment]
This is an easy fix AFAICT -- just authored and tested #9 on my local Windows 10 machine, and things seem to work as intended.
