### ISSUE TITLE
[feature request] Move highlight line inside the context viewer

### ISSUE THREAD

**Issue by wilbeibi** [konradsz/igrep#40]
Something similar to `tig`.

**Comment by konradsz** [comment]
Hey, sorry for the late response. Could you explain that in a more detailed way? Would like to move around the file in which `igrep` found a match in the context viewer?

**Comment by liming01** [comment]
I  think he wants to scroll up/down the context viewer.

The scroll focus can be in the main viewer or in the context viewer, there are 2 ways:

- Like [tig](https://github.com/jonas/tig/),  the scroll focus will switch from the main viewer to the context viewer, then you can use the key `j`/`k`/`h`/`l` to scroll the context viewer. And need `Esc` to switch the scroll focus back to the main viewer.

- Like [yazi](https://github.com/sxyazi/yazi), the scroll focus is always on the main viewer, use the key `ctrl`+`j`/`k` to scroll the the context viewer.

**Comment by konradsz** [comment]
If that is the case I would be opposed to adding such a feature. I want `igrep` to be a lightweight "proxy" between (rip-)grep and user's editor. Current context viewer should be enough to determine whether you want to dig deeper into the file or just move further with your search results :)
