### ISSUE TITLE
Support multiple PATH arguments

### ISSUE THREAD

**Issue by rlue** [konradsz/igrep#42]
Hi, very cool project. Are there any plans to support multiple PATH arguments in the future? _I.e.,_ the following command line fails:

```sh
$ ig query . /tmp
error: Found argument '/tmp' which wasn't expected, or isn't valid in this context
```

where passing the same arguments to `rg` searches for instances of "query" in both the current directory and `/tmp`. POSIX grep also does this, as long as you pass it the `-r` flag.

**Comment by konradsz** [comment]
Hi, I added support for multiple path search, it wasn't there from the beginning simply because I never used grep/ripgrep this way. Happy searching! ;)
