### ISSUE TITLE
Custom editor command?

### ISSUE THREAD

**Issue by ncfavier** [konradsz/igrep#53]
I would like to use igrep to search my WeeChat logs interactively, and I would like to be able to view said logs using a pager rather than an editor. This is so that I don't edit them accidentally, and also so that ANSI escape sequences are displayed correctly.

You could add a `less` editor option following the `vim` one, but it would make more sense to make the editor command fully configurable so that we don't have to hardcode every editor and pager in the universe.

**Comment by konradsz** [comment]
I am going to try to provide an option to specify a custom command alongside predefined editors. Let's see how it pans out ;)
