### ISSUE TITLE
Follow symlinks?

### ISSUE THREAD

**Issue by Nindaleth** [konradsz/igrep#59]
Just recently discovered igrep and it scratches one of my itches that was very hard to get rid of for me. Thanks for making this.

I was wondering if you'd be willing to add `-L/--follow` option that allows to follow symlinks; currently the dir symlinks aren't searchable if pointing outside of the searched directory subtree.

**Comment by konradsz** [comment]
Sure thing, it will be available in a next release.

**Comment by Nindaleth** [comment]
That's great, thanks a lot!
