### ISSUE TITLE
Support for emacs / spacemacs ?

### ISSUE THREAD

**Issue by bryandmc** [konradsz/igrep#6]
I would definitely use this if I could pass `emacsclient -nw` to the editor to be able to load the results in emacs.. Probably requires so extra options so that it opens the stuff in the right place but I'm sure it's a pretty easy addition. I'd recommend an `emacs` and `emacsclient` option but probably both should use the -nw (terminal only) option but that's debatable.. 

Thanks!

**Comment by konradsz** [comment]
Emacs support was not added so far because I know nothing about it 😅 but I will treat it as an opportunity to change this.
