### ISSUE TITLE
--custom-command  and IGREP_CUSTOM_EDITOR not working

### ISSUE THREAD

**Issue by BrayanLope5** [konradsz/igrep#66]
I am on Arch Linux, I tried using both `--custom-command`  and `IGREP_CUSTOM_EDITOR` but neither seem to be working. I use fish as my shell and wezterm as my terminal.

When I try the environment variable, `ig` ignores it completely. When I try `--custom-command`, I just get the following error.
![out_3](https://github.com/konradsz/igrep/assets/74095547/c3effdc2-51fc-468a-9afb-eb8648155cf4).

Let me know if there is any more information I can provide.

**Comment by konradsz** [comment]
`--custom-command` will be available in the next version, which I am going to release soon. Sorry for the confusion, I need to be more precise in README in the future.
