### ISSUE TITLE
Debian package?

### ISSUE THREAD

**Issue by midenok** [konradsz/igrep#68]
Scoop? Homebrew? And no Debian/Ubuntu? Sad...

**Comment by konradsz** [comment]
I would love to have `igrep` available for every distro/system, but I can't afford it (time-wise). Currently available packages are prepared by volunteers. I encourage people to build it from source - the more people have Rust toolchain on their computers the merrier :)

**Comment by midenok** [comment]
Sorry, no. I'm aware of igrep 5+- years and never used it as I can use grep or any RAD tools and I will not spend time on installation or keep a lot of unused packages just because of some small handy tool.
