### ISSUE TITLE
Use $EDITOR by default if set

### ISSUE THREAD

**Issue by mre** [konradsz/igrep#7]
On Unix-like operating systems like Linux or macOS an environment variable named `$EDITOR` can be set, which defines the default editor to be used.
This variable gets used by tools like git if it isn't overwritten by the config.
Something similar could be done for igrep.
The advantage is that users can change their editor in one place and it would be used by many tools.

Here is a code-snippet that shows how to open a file:
https://github.com/mre/envy/blob/43464b8f351a00f4030a5e1b84e846b1c3ac54ab/src/main.rs#L52-L56

If $EDITOR is not set, a fallback could still be used and the setting should still be overwriteable from the commandline of course.

**Comment by konradsz** [comment]
The plan is to use `$EDITOR` as a fallback option if neither `--editor` nor `IGREP_EDITOR` is set. I will take care of implementation soon.

**Comment by mre** [comment]
Even better, thanks!
